run:
  timeout: 5m
issues:
  exclude-use-default: false
linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - goimports
    - ineffassign
    - errcheck
    - typecheck
    - unused
    - deadcode
    - structcheck
    - varcheck
    - misspell
    - unconvert
    - unparam
    - dupl
    - gocritic
    - gosec
    - prealloc
    - stylecheck
    - whitespace
