# .goreleaser.yaml
project_name: brains

builds:
  - id: brains
    main: ./cmd/cli         
    binary: brains          
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    files:
      - LICENSE.md
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

