project_name: brains
version: 2

builds:
  - id: brains-linux-windows
    main: ./cmd/cli
    binary: brains
    env:
      - CGO_ENABLED=1
    goos: [linux, windows]
    goarch: [amd64, arm64]
    tags: [netgo, osusergo]
    overrides:
      # Linux musl (no glibc/libresolv needed)
      - goos: linux
        goarch: amd64
        env:
          - CC=zig cc -target x86_64-linux-musl
          - CXX=zig c++ -target x86_64-linux-musl
      - goos: linux
        goarch: arm64
        env:
          - CC=zig cc -target aarch64-linux-musl
          - CXX=zig c++ -target aarch64-linux-musl
      # Windows
      - goos: windows
        goarch: amd64
        env:
          - CC=zig cc -target x86_64-windows-gnu
          - CXX=zig c++ -target x86_64-windows-gnu
      - goos: windows
        goarch: arm64
        env:
          - CC=zig cc -target aarch64-windows-gnu
          - CXX=zig c++ -target aarch64-windows-gnu

archives:
  - id: default
    formats: [tar.gz]
    wrap_in_directory: true
    files:
      - LICENSE.md
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
